# image Elasticsearch
FROM docker.elastic.co/elasticsearch/elasticsearch:8.10.3

# Copie du fichier de configuration elasticsearch.yml 
COPY elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
